# permissions for end users to view matrices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: matrix-viewer-role
rules:
- apiGroups:
  - charts.opdev.io
  resources:
  - matrices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.opdev.io
  resources:
  - matrices/status
  verbs:
  - get
