# permissions for end users to edit synapses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synapse-editor-role
rules:
- apiGroups:
  - charts.opdev.io
  resources:
  - synapses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.opdev.io
  resources:
  - synapses/status
  verbs:
  - get
